inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/bundle/**/*
  SuggestExtensions: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line
  SupportedTypes: ["block"]

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - lib/panchira/resolvers/*

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - panchira.gemspec

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets
